"""empty message

Revision ID: 1fa7f7640471
Revises: None
Create Date: 2016-01-17 13:32:12.943356

"""

# revision identifiers, used by Alembic.
revision = '1fa7f7640471'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_detail',
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_no', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_detail')
    ### end Alembic commands ###
