"""empty message

Revision ID: 8822d6e22f43
Revises: None
Create Date: 2016-01-15 13:52:33.776295

"""

# revision identifiers, used by Alembic.
revision = '8822d6e22f43'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_detail',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_detail')
    ### end Alembic commands ###
